name: utmschedular
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  flutter:
    sdk: flutter
  http: ^0.13.6
  #Calendar depandencies
  table_calendar: ^3.0.9
  # Firebase auth and firebase core
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/profile_icon.png
    - images/menu_icon.png
    - images/timetable_icon.png
    - images/delete_icon.png
    - images/plus_icon.png