name: utmschedular
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.8.0
  flutter:
    sdk: flutter
  http: ^0.13.6
  #Calendar depandencies
  table_calendar: ^3.0.9
  # Firebase auth and firebase core
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  provider: ^6.0.5
  firebase_database: ^10.2.2
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true

  assets:
    - images/profile_icon.png
    - images/menu_icon.png
    - images/timetable_icon.png
    - images/delete_icon.png
    - images/plus_icon.png
